# HW 2 - Simple Neural Networks

Part 1: In this first real coding assignment, you will initially explore the operation of a single perceptron (more for historical value than for modern usefulness) and a single Sigmoid neuron to implement the "real world" example of going to a cheese festival.

Part 2: In the second part, you will switch over to using the author's code to complete a full neural network that can recognize handwritten digits. You will train and run the network monitoring both how long it takes to train AND the test accuracy once training is complete.

Part 3: In the third part, you will experiment with hyper-parameters such as the number of epochs, the batch size, and the learning rate. Again, you will monitor the training time and the test accuracy after training is complete.

Part 4: In the final part, you will experiment with the network structure itself by changing the number of neurons in the hidden layer. You will again report the training time and test accuracy, but this time you will also report the evaluation time.


In [2]:
from abc import abstractmethod
class Neuron:
  def __init__(self, w, b):
    self.w = w
    self.b = b

  @abstractmethod
  def output(self, x):
    pass

In [3]:
import math

class Perceptron(Neuron):
  def __init__(self, w, b):
    super().__init__(w, b)

  """
    x: list of inputs ... must be same length as w
    return 0 or 1 based on classic perceptron calculation weighted sum of inputs plus bias must be strictly greater than 0 to produce a 1 otherwise return a 0
  """
  def output(self, x):
    z = 0
    for i in range(len(self.w)):
      z = z + self.w[i]*x[i]
    z = z + self.b
    return 0 if z <= 0 else 1

class SigmoidNeuron(Neuron):
  def __init__(self, w, b):
    super().__init__(w, b)

  """
    x: list of inputs ... must be same length as w
    return 0 or 1 based on classic perceptron calculation weighted sum of inputs plus bias must be strictly greater than 0 to produce a 1 otherwise return a 0
  """
  def output(self, x):
    z = 0
    for i in range(len(self.w)):
      z = z + self.w[i]*x[i]
    z = z + self.b
    return 1/(1+math.exp(-z))


In [9]:
# PART 1a - instantiate a single Perceptron with the weights described in Chapter 1 for going to the festival. Then print out the output of calling the "output" function on that neuron with three combinations of inputs for the weather, girlfiend, and public transit inputs.
p = Perceptron([6,2,2], -5)
x = [1, 1, 1]
a = p.output(x)
print(a)
x = [0, 1, 1]
a = p.output(x)
print(a)

# PART 2b - repeat Part1a, but this time use a SigmoidNueron instead. Compare the output with Part 1a and explain in a comment how this part using a SigmoidNeuron could still give you the "right" answer about whether to go or not.
m = SigmoidNeuron([6,2,2], -5)
x = [1, 1, 1]
a = m.output(x)
print(a)
x = [0, 1, 1]
a = m.output(x)
print(a)

1
0
0.9933071490757153
0.2689414213699951


In [10]:
# PART 2 - run the code below to download your author's code and then train and evaluate the network. ****Make note of the total training time and test accuracy****
#%cd /content 
%cd "/workspaces/cosc470/" 
!pwd
!git clone "https://github.com/MichalDanielDobrzanski/DeepLearningPython" nn





/workspaces/cosc470
/workspaces/cosc470
Cloning into 'nn'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 63 (delta 30), reused 28 (delta 28), pack-reused 21 (from 1)
Receiving objects: 100% (63/63), 16.43 MiB | 54.98 MiB/s, done.
Resolving deltas: 100% (31/31), done.


In [25]:
# load the data into memory (training_data and test_data numpy arrays)
%cd nn
import mnist_loader
training_data, validation_data, test_data = mnist_loader.load_data_wrapper()
training_data = list(training_data)
test_data = list(test_data)
print(len(training_data))
print(len(test_data))
import numpy as np
np.set_printoptions(linewidth=400)
firstimage = np.reshape(training_data[5][0],(28,28))
firstimage_r = np.round(firstimage, decimals=2)

print(firstimage_r)
print(training_data[5][1])

[Errno 2] No such file or directory: 'nn'
/workspaces/cosc470/nn
50000
10000
[[0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.05 0.1  0.39 0.48 0.03 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 

In [35]:
# default run with default hyperparameters - 20 epochs, batch size of 10, and learning rate of 3.0

import importlib
import network
importlib.reload(network)
net = network.Network([784, 30, 10])
print(training_data[800][1])
print(net.feedforward(training_data[800][0]))

#print(net.weights)
#print(net.biases)
net.SGD(training_data, 5, 10, 3.0, test_data=test_data)

print(net.feedforward(training_data[800][0]))


[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
[[0.44907995]
 [0.81396429]
 [0.00707575]
 [0.90054124]
 [0.95473681]
 [0.99452011]
 [0.7195206 ]
 [0.93552346]
 [0.00797964]
 [0.31355213]]
Epoch 0 : 9091 / 10000
Epoch 1 : 9190 / 10000
Epoch 2 : 9310 / 10000
Epoch 3 : 9381 / 10000
Epoch 4 : 9385 / 10000
[[5.79162915e-06]
 [3.36437449e-05]
 [1.00423774e-05]
 [2.70432798e-03]
 [2.72294294e-02]
 [2.09932846e-05]
 [3.91087475e-06]
 [6.34732296e-03]
 [6.96106525e-03]
 [9.82534650e-01]]


In [ ]:
# PART 3 - experiment with the hyperparameters ... try the following combinations
# Varying the number of epochs: 5, 10, 15, 30 (see below)
# 5, 10, 3.0
# 10, 10, 3.0
# 15, 10, 3.0
# 30, 10, 3.0

# Varying the batch size: 5, 20, 30
# 20, 5, 3.0
# 20, 20, 3.0
# 20, 30, 3.0

# Varying the learning rate: 2.5, 3.5, 4.0
# 20, 10, 2.5
# 20, 10, 3.5
# 20, 10, 4.0


# After all 10 RUNS plus your original run with the defaults (20, 10, 3.0), plot your timing results and final test accuracy in a single chart using matplotlib



In [ ]:
# PART 4 - experiment with network structure, just try three different configurations
# [784, 10, 10], [784, 50, 10], and [784, 100, 10]

# After these 3 runs, plot your training timing results, test accuracy, AND evaluation timing
# To measure the evaluation time, manually test 100 samples from the test dataset, measure how long that takes and divide by 100 to get a per/image evaluate rate

# Use Matplotlib to plot ALL THREE results (training time, test accuracy, and evaluation rate) on three different axes
